// Central registry of every Mongoose model in the system. Importing this file once at boot
// guarantees every schema is registered with Mongoose before any route handles a request
// (avoids the classic "Schema hasn't been registered for model X" error from lazy requires),
// and gives the schema explorer one place to introspect every collection by name.

module.exports = {
  User: require('./User'),
  Hotel: require('./Hotel'),
  Room: require('./Room'),
  RoomRate: require('./RoomRate'),
  RatePlan: require('./RatePlan'),
  Booking: require('./Booking'),
  Folio: require('./Folio'),
  Deposit: require('./Deposit'),
  Document: require('./Document'),
  ServiceCatalog: require('./ServiceCatalog'),
  ServiceRequest: require('./ServiceRequest'),
  Table: require('./Table'),
  MenuItem: require('./MenuItem'),
  Order: require('./Order'),
  HousekeepingTask: require('./HousekeepingTask'),
  LostFound: require('./LostFound'),
  LaundryRequest: require('./LaundryRequest'),
  TransportRequest: require('./TransportRequest'),
  Hall: require('./Hall'),
  EventBooking: require('./EventBooking'),
  InventoryItem: require('./InventoryItem'),
  StockTransaction: require('./StockTransaction'),
  Supplier: require('./Supplier'),
  PurchaseRequest: require('./PurchaseRequest'),
  PurchaseOrder: require('./PurchaseOrder'),
  Staff: require('./Staff'),
  Attendance: require('./Attendance'),
  Shift: require('./Shift'),
  LeaveRequest: require('./LeaveRequest'),
  MaintenanceTicket: require('./MaintenanceTicket'),
  Equipment: require('./Equipment'),
  Expense: require('./Expense'),
  Complaint: require('./Complaint'),
  Review: require('./Review'),
  Notification: require('./Notification'),
  AuditLog: require('./AuditLog'),
  Setting: require('./Setting'),
  NightAudit: require('./NightAudit'),
  BackupLog: require('./BackupLog'),
};