// Maps every entity name from the spec's canonical list to what it actually became in this
// codebase — a real table for the schema explorer UI, not a comment buried in a model file.

const ENTITY_MAP = [
  { entity: 'users', model: 'User', note: 'Includes both staff and guests (role field distinguishes them)' },
  { entity: 'roles', model: null, note: 'Defined as a fixed enum + config/permissionMatrix.js, not a DB collection' },
  { entity: 'permissions', model: null, note: 'config/permissionMatrix.js — single source of truth, see Part 16' },
  { entity: 'role_permissions', model: null, note: 'Same file as permissions — the matrix IS the join table, expressed as code' },
  { entity: 'hotels', model: 'Hotel', note: 'Single-property by default; model supports multi-property if needed' },
  { entity: 'room_types', model: 'Room', note: 'Implemented as Room.roomType enum, not a separate table' },
  { entity: 'rooms', model: 'Room' },
  { entity: 'room_amenities', model: 'Room', note: 'Room.amenities[] array field, not a join table' },
  { entity: 'room_rates', model: 'RoomRate + RatePlan', note: 'Base rates + seasonal/holiday/corporate/promo plans' },
  { entity: 'guests', model: 'User', note: 'Guests are User documents with role="customer"' },
  { entity: 'guest_documents', model: 'Document', note: 'docType="guest_id", access-restricted, see Part 13' },
  { entity: 'reservations', model: 'Booking' },
  { entity: 'reservation_rooms', model: 'Booking', note: 'Booking.rooms[] array supports multi-room/group bookings' },
  { entity: 'check_ins', model: 'Booking', note: 'Booking.actualCheckInTime field, not a separate table' },
  { entity: 'check_outs', model: 'Booking', note: 'Booking.actualCheckOutTime field' },
  { entity: 'guest_folios', model: 'Folio' },
  { entity: 'folio_items', model: 'Folio', note: 'Folio.charges[] embedded subdocuments' },
  { entity: 'payments', model: 'Folio + Deposit', note: 'Folio.payments[] for in-stay charges, Deposit for advances' },
  { entity: 'refunds', model: 'Deposit', note: 'Deposit.refundStatus/refundAmount fields' },
  { entity: 'invoices', model: 'Folio', note: 'Folio.getBreakdown() + verificationCode for QR verification' },
  { entity: 'services', model: 'ServiceCatalog', note: 'Added in Part 18 to close a real gap' },
  { entity: 'service_requests', model: 'ServiceRequest' },
  { entity: 'restaurant_tables', model: 'Table' },
  { entity: 'menu_categories', model: 'MenuItem', note: 'MenuItem.category string field, not a separate table' },
  { entity: 'menu_items', model: 'MenuItem' },
  { entity: 'orders', model: 'Order' },
  { entity: 'order_items', model: 'Order', note: 'Order.items[] embedded subdocuments' },
  { entity: 'kitchen_orders', model: 'Order', note: 'Same document; Order.status drives the KOT workflow (new→...→served)' },
  { entity: 'housekeeping_tasks', model: 'HousekeepingTask' },
  { entity: 'lost_found', model: 'LostFound' },
  { entity: 'laundry_orders', model: 'LaundryRequest' },
  { entity: 'transport_requests', model: 'TransportRequest' },
  { entity: 'events', model: 'Hall', note: 'Bookable venues (banquet halls, conference rooms)' },
  { entity: 'event_bookings', model: 'EventBooking' },
  { entity: 'inventory_items', model: 'InventoryItem' },
  { entity: 'inventory_transactions', model: 'StockTransaction' },
  { entity: 'suppliers', model: 'Supplier' },
  { entity: 'purchase_orders', model: 'PurchaseOrder' },
  { entity: 'purchase_order_items', model: 'PurchaseOrder', note: 'PurchaseOrder.items[] embedded subdocuments' },
  { entity: 'employees', model: 'Staff', note: 'Extends User with department/designation/documents' },
  { entity: 'attendance', model: 'Attendance' },
  { entity: 'shifts', model: 'Shift' },
  { entity: 'leave_requests', model: 'LeaveRequest' },
  { entity: 'maintenance_requests', model: 'MaintenanceTicket' },
  { entity: 'equipment', model: 'Equipment' },
  { entity: 'expenses', model: 'Expense' },
  { entity: 'complaints', model: 'Complaint' },
  { entity: 'reviews', model: 'Review' },
  { entity: 'notifications', model: 'Notification' },
  { entity: 'audit_logs', model: 'AuditLog' },
  { entity: 'settings', model: 'Setting' },
];

module.exports = { ENTITY_MAP };